### ISSUE TITLE
on-disk data structures

### ISSUE THREAD

**Issue by SoniEx2** [google/guava#3587]
it would be fairly powerful to have data structures optimized for on-disk manipulation.

just open a data structure on top of a path and do stuff with it.

**Comment by kluever** [comment]
This request doesn't contain info detail for us to do anything with it.

**Comment by SoniEx2** [comment]
fixed

**Comment by kluever** [comment]
The request is still very vague (which data structures? why is this important? why should we add this to Guava?). In any case, I'm still not sure this is something suitable for Guava.

**Comment by SoniEx2** [comment]
things like an on-disk list of integers that can be efficiently sorted, or an efficient on-disk map. stuff for operating on large datasets that don't cleanly fit into RAM.
